version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Brussels
  open-pull-requests-limit: 0
  reviewers:
  - Olympic1
  labels:
  - Pull request
  - Dependencies
